result_dir: './result'
exp_name: 'gtm_sm'
train_dir: './datasets/CelebA/training'
val_dir: './datasets/CelebA/val'
test_dir: './datasets/CelebA/testing'
ckpt_dir: ''
accelerator: 'ddp'

data:
  inp_channel: 3
  img_h: 8
  img_w: 8

train:
  batch_size: 16
  max_epochs: 100
  seed: 2018
  lr: 1e-3
  gpus: [5]
  num_workers: 12
  check_val_every_n_epoch: 1
  gradient_clip_val: 5.
  limit_val_batches: 1.

log:
  save_epoch_freq: 10
  print_step_freq: 256

gtm_sm:
  a_dim: 5
  s_dim: 2
  z_dim: 16
  observe_dim: 256
  total_dim: 288
  r_std: 0.001
  knn: 5
  delta: 1e-4
  kl_samples: 1000
  training_wo_wall: True
  
  vae:
    model_path: ''
  